// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl8gBuazUcZI8NgKJa05V34LJdza6weoc',
    appId: '1:178356227708:web:19e4d4c0bd351c8d5bc3f9',
    messagingSenderId: '178356227708',
    projectId: 'flutter-firebase-e042a',
    authDomain: 'flutter-firebase-e042a.firebaseapp.com',
    storageBucket: 'flutter-firebase-e042a.appspot.com',
    measurementId: 'G-WHT3XYWK6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCee468suIiZL0C-ArWnSnDsMdyQeGdI1o',
    appId: '1:178356227708:android:68bdc9a9df0291155bc3f9',
    messagingSenderId: '178356227708',
    projectId: 'flutter-firebase-e042a',
    storageBucket: 'flutter-firebase-e042a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjhO0eroBy4flZ4ZNMYX1FodEuPdYaxxY',
    appId: '1:178356227708:ios:eaea7815b55d20375bc3f9',
    messagingSenderId: '178356227708',
    projectId: 'flutter-firebase-e042a',
    storageBucket: 'flutter-firebase-e042a.appspot.com',
    iosClientId: '178356227708-0sm4s00lv2uaedb0o18on7lr8ah65sha.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjhO0eroBy4flZ4ZNMYX1FodEuPdYaxxY',
    appId: '1:178356227708:ios:de9509ab24f2dc235bc3f9',
    messagingSenderId: '178356227708',
    projectId: 'flutter-firebase-e042a',
    storageBucket: 'flutter-firebase-e042a.appspot.com',
    iosBundleId: 'com.example.bookbox.RunnerTests',
  );
}
