// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfro89hcVJpWycU8Ko_R1BA45-8qh4Y10',
    appId: '1:553575107355:web:b85b730808b430bad261be',
    messagingSenderId: '553575107355',
    projectId: 'bookbox-2d0f7',
    authDomain: 'bookbox-2d0f7.firebaseapp.com',
    storageBucket: 'bookbox-2d0f7.appspot.com',
    measurementId: 'G-7397FB9LZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoF2tuK0cZMQb9ecmBkhPVVdUe_biateE',
    appId: '1:553575107355:android:f748f738fe958a76d261be',
    messagingSenderId: '553575107355',
    projectId: 'bookbox-2d0f7',
    storageBucket: 'bookbox-2d0f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx9SXmZS_xNmfO324iG8YlsEGN_H8xptQ',
    appId: '1:553575107355:ios:a0909f0fef5ad7ead261be',
    messagingSenderId: '553575107355',
    projectId: 'bookbox-2d0f7',
    storageBucket: 'bookbox-2d0f7.appspot.com',
    iosBundleId: 'com.example.bookbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx9SXmZS_xNmfO324iG8YlsEGN_H8xptQ',
    appId: '1:553575107355:ios:c552fd55915aeffcd261be',
    messagingSenderId: '553575107355',
    projectId: 'bookbox-2d0f7',
    storageBucket: 'bookbox-2d0f7.appspot.com',
    iosBundleId: 'com.example.bookbox.RunnerTests',
  );
}
